---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2022-01-28T10:30:57.227311+01:00"
  name: flux-fundamentals
  namespace: jsmit
spec:
  gitImplementation: go-git
  interval: 10m0s
  ref:
    branch: main
  secretRef:
    name: flux-fundamentals
  timeout: 20s
  url: https://github.com/jeroensmit/gitops-fundamentals-exercises

